
CREATE VIEW `bitcms_detailreviewview` AS select `bitcms_review`.`reviewid` AS `reviewid`,`bitcms_review`.`userid` AS `userid`,`bitcms_review`.`detailid` AS `detailid`,`bitcms_review`.`channelcode` AS `channelcode`,`bitcms_review`.`replyid` AS `replyid`,`bitcms_review`.`title` AS `title`,`bitcms_review`.`content` AS `content`,`bitcms_review`.`show` AS `show`,`bitcms_review`.`verify` AS `verify`,`bitcms_review`.`replynum` AS `replynum`,`bitcms_review`.`hitsnum` AS `hitsnum`,`bitcms_review`.`againstnum` AS `againstnum`,`bitcms_review`.`agreenum` AS `agreenum`,`bitcms_review`.`indate` AS `indate`,`bitcms_detail`.`title` AS `detailtitle`,`bitcms_detail`.`resume` AS `resume`,`bitcms_detail`.`galleryid` AS `galleryid`,`bitcms_review`.`secrecy` AS `secrecy` from (`bitcms_review` join `bitcms_detail` on((`bitcms_review`.`detailid` = `bitcms_detail`.`detailid`)));

CREATE VIEW  `bitcms_userdetailview` AS select `bitcms_detail`.`detailid` AS `detailid`,`bitcms_detail`.`itemid` AS `itemid`,`bitcms_detail`.`items` AS `items`,`bitcms_detail`.`userid` AS `userid`,`bitcms_detail`.`channelcode` AS `channelcode`,`bitcms_detail`.`title` AS `title`,`bitcms_detail`.`subtitle` AS `subtitle`,`bitcms_detail`.`display` AS `display`,`bitcms_detail`.`show` AS `show`,`bitcms_detail`.`resume` AS `resume`,`bitcms_detail`.`keyword` AS `keyword`,`bitcms_detail`.`searchkey` AS `searchkey`,`bitcms_detail`.`galleryid` AS `galleryid`,`bitcms_detail`.`closereview` AS `closereview`,`bitcms_detail`.`enabledlink` AS `enabledlink`,`bitcms_detail`.`link` AS `link`,`bitcms_detail`.`againstnum` AS `againstnum`,`bitcms_detail`.`agreenum` AS `agreenum`,`bitcms_detail`.`follownum` AS `follownum`,`bitcms_detail`.`hitsnum` AS `hitsnum`,`bitcms_detail`.`reviewnum` AS `reviewnum`,`bitcms_detail`.`recycle` AS `recycle`,`bitcms_detail`.`recycledate` AS `recycledate`,`bitcms_detail`.`author` AS `author`,`bitcms_detail`.`source` AS `source`,`bitcms_detail`.`indate` AS `indate`,`bitcms_user`.`username` AS `username`,`bitcms_user`.`avatar` AS `avatar`,`bitcms_detail`.`stars` AS `stars`,`bitcms_detail`.`detailcode` AS `detailcode`,`bitcms_detail`.`displaytime` AS `displaytime`,`bitcms_detail`.`readpower` AS `readpower`,`bitcms_detail`.`gallerystatistics` AS `gallerystatistics`,`bitcms_item`.`itemname` AS `itemname`,`bitcms_item`.`icon` AS `icon` from ((`bitcms_detail` join `bitcms_user` on((`bitcms_detail`.`userid` = `bitcms_user`.`userid`))) join `bitcms_item` on((`bitcms_detail`.`itemid` = `bitcms_item`.`itemid`)));

CREATE VIEW  `bitcms_userreviewview` AS select `bitcms_review`.`reviewid` AS `reviewid`,`bitcms_review`.`userid` AS `userid`,`bitcms_review`.`detailid` AS `detailid`,`bitcms_review`.`channelcode` AS `channelcode`,`bitcms_review`.`replyid` AS `replyid`,`bitcms_review`.`content` AS `content`,`bitcms_review`.`verify` AS `verify`,`bitcms_review`.`replynum` AS `replynum`,`bitcms_review`.`againstnum` AS `againstnum`,`bitcms_review`.`agreenum` AS `agreenum`,`bitcms_review`.`indate` AS `indate`,`bitcms_user`.`username` AS `username`,`bitcms_user`.`avatar` AS `avatar`,`bitcms_review`.`title` AS `title`,`bitcms_review`.`show` AS `show`,`bitcms_review`.`hitsnum` AS `hitsnum`,`bitcms_review`.`secrecy` AS `secrecy` from (`bitcms_review` join `bitcms_user` on((`bitcms_review`.`userid` = `bitcms_user`.`userid`)));

CREATE VIEW `bitcms_userview` AS select `bitcms_user`.`userid` AS `userid`,`bitcms_user`.`username` AS `username`,`bitcms_user`.`roleid` AS `roleid`,`bitcms_user`.`birthday` AS `birthday`,`bitcms_user`.`gender` AS `gender`,`bitcms_user`.`avatar` AS `avatar`,`bitcms_user`.`location` AS `location`,`bitcms_user`.`cityid` AS `cityid`,`bitcms_user`.`city` AS `city`,`bitcms_user`.`lockuser` AS `lockuser`,`bitcms_user`.`score` AS `score`,`bitcms_user`.`ip` AS `ip`,`bitcms_user`.`indate` AS `indate`,`bitcms_user`.`introduce` AS `introduce`,`bitcms_user`.`lastLanddate` AS `lastLanddate`,`bitcms_user`.`verifymember` AS `verifymember`,`bitcms_user`.`comefrom` AS `comefrom`,`bitcms_role`.`rolename` AS `rolename`,`bitcms_role`.`roletype` AS `roletype`,`bitcms_user`.`show` AS `show`,`bitcms_user`.`deadline` AS `deadline`,`bitcms_user`.`follownum` AS `follownum` from (`bitcms_user` join `bitcms_role` on((`bitcms_user`.`roleid` = `bitcms_role`.`roleid`)));

DELIMITER $$
CREATE FUNCTION `DiffDays`(d1 datetime,d2 datetime) RETURNS int(11)
BEGIN
 RETURN DATEDIFF(d1,d2);
END $$
DELIMITER ;


